site_name: Notes
site_description: Learning notes.
site_author: ShenMian
repo_url: https://github.com/ShenMian/Notes/

theme:
  name: material

  features:
    - navigation.tabs

  # 404 页面
  static_templates:
    - 404.html

  # 配色
  palette:
    # 浅色模式
    - scheme: default
      primary: green
      toggle:
        icon: material/brightness-7 
        name: 浅色模式

    # 深色模式
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: 深色模式

  # 启用搜索功能
  include_search_page: false
  search_index_only: true

  # 默认值, 来自于 mkdocs_theme.yml
  language: zh
  font:
    code: Cascadia Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
