site_name: Notes
site_description: Learning notes.
site_author: ShenMian
site_url: https://shenmian.github.io/Notes/

repo_name: ShenMian/Notes
repo_url: https://github.com/ShenMian/Notes/

# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  language: zh