site_name: Notes
site_description: Learning notes.
site_author: ShenMian
site_url: https://shenmian.github.io/Notes/

repo_name: ShenMian/Notes
repo_url: https://github.com/ShenMian/Notes/

# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material

  # 语言
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/?h=language#configuration
  language: zh

  # 字体
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=font#configuration
  font:
    text: Cascadia Mono
    code: Cascadia Mono

  # 启用搜索功能
  include_search_page: false
  search_index_only: true

  # 404 页面
  static_templates:
    - 404.html

  # 配色
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=palette#color-palette-toggle
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7 
        name: 浅色模式
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: 深色模式

  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=features+navigation+tabs#navigation-tabs
    - navigation.tabs

# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=extra+social#social-links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShenMian
    - icon: fontawesome/brands/telegram
      link: https://t.me/ShenMian
  alternate:
    - name: Chinese
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en

