site_name: Notes
repo_url: https://github.com/ShenMian/Notes/

theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  palette:
    scheme: slate

  # 启用搜索功能
  include_search_page: false
  search_index_only: true

  # 默认值, 来自于 mkdocs_theme.yml
  language: zh
  font:
    code: Cascadia Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
