name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate HTML from Markdown
      uses: ldeluigi/markdown-docs@latest
      with:
        src: .
        dst: ./docs
        language: zh
        primary-color: indigo
        secondary-color: indigo

    - name: Deploy
      run: |
        pip install mkdocs-material 
        mkdocs gh-deploy --force

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./docs
