name: Generate HTML

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate HTML from Markdown
      uses: ldeluigi/markdown-docs@latest
      with:
        src: .
        dst: ./docs
        language: zh
        primary-color: indigo
        secondary-color: indigo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: true
